Feature - User list frontend
juvigh/onboarding-frontend pull request #14
Opened 2023-08-14 13:03 UTC by juvigh

<img width="1280" alt="Captura de Tela 2023-08-14 às 09 46 39" src="https://github.com/juvigh/onboarding-frontend/assets/101653937/7f0fcadb-9de8-4a9e-aaf4-8920560293c1">

2023-08-14 13:59 UTC, SamuelSsc commented on src/components/user-list/user-list-styles.ts
> +  border-bottom: ${({ hasBorderBottom }) =>
Se o seu `hasBorderBottom` for false, esse estilo vai chegar no DOM quebrado, algo como:
**<strike>border-bottom: ;</strike>**  
Para que ele não chegue assim quando for false vc pode colocar o estilo dentro da condição, assim ele só altera e vai para o DOM quando for verdadeiro.
```suggestion
 ${({ hasBorderBottom }) => hasBorderBottom &&  border-bottom: 
```

2023-08-14 13:59 UTC, SamuelSsc commented on src/components/user-list/user-list.tsx
> +      <div className="title">
👀

2023-08-14 14:01 UTC, SamuelSsc commented on src/components/user-list/user-list-styles.ts
> +  .title {
Aqui como estamos usando o Style Components para criar componentes estilizados, não usamos classNames para estilizar componentes filhos, mas criamos tbm um estilo pra ele.

2023-08-14 14:05 UTC, SamuelSsc requested changes

2023-08-14 14:05 UTC, SamuelSsc commented on src/components/user-list/user-list-styles.ts
> +  h1 {
Aqui tbm para estilizar ao inves de colocar o nome do componente filho assim cria uma const de estilo propria pra ele, assim vc vai poder usar em outros lugares se precisar e a const de estilo `UserListConteiner`, vai atribuir estilo para sua única responsabilidade que é o container da lista.

2023-08-14 14:05 UTC, SamuelSsc commented on src/components/user-list/user-list-styles.ts
> +  p {
O mesmo aqui, cria uma const de estilo próprio, assim cada const tem uma única responsabilidade.

2023-08-14 16:10 UTC, juvigh commented on src/components/user-list/user-list-styles.ts
> +  h1 {
<img width="1280" alt="Captura de Tela 2023-08-14 às 13 09 02" src="https://github.com/juvigh/onboarding-frontend/assets/101653937/61eccde7-e700-4a55-ba3f-4c132a07f281">

apliquei e o estilo continua o mesmo 👍

2023-08-15 14:13 UTC, SamuelSsc commented on src/components/loading/loading-indicador.tsx
> +  return (
nit: como essa função não faz nenhuma lógica e apenas retorna um componente vc pode retornar de maneira implicita.
```suggestion
export const LoadingIndicator = () => (
```

2023-08-15 14:14 UTC, SamuelSsc commented on src/components/loading/loading-styles.ts
> +  img {
Aqui para a imagem tbm pode criar um estilo próprio, para não deixar aninhado ao estilo do container.

2023-08-15 14:16 UTC, SamuelSsc commented on src/components/user-list/user-list-styles.ts
> +  h3,
Aqui vc continua aninhando o estilo do seu h3 e p ao estilo do `UserItemContainer`. Na vdd vi que vc criou o estilo kk, faltou só apagar aqui.

2023-08-15 14:21 UTC, SamuelSsc commented on src/styles/paragraph.ts
> +import styled from 'styled-components';
poderia deixar headings e paragraph no mesmo arquivo, pois ambos são tipografias de texto.

2023-08-15 14:23 UTC, SamuelSsc approved these changes

2023-08-15 17:47 UTC, juvigh commented on src/components/user-list/user-list-styles.ts
> +  h3,
pior que eu fui perceber em outra branch e apaguei haha

2023-08-15 18:24 UTC, merged